{"name": "test_input[warvictimsfund]", "status": "broken", "statusDetails": {"message": "TypeError: ContactForm.input_field() takes 2 positional arguments but 4 were given", "trace": "field_data_dict = 'warvictimsfund'\n\n    @pytest.mark.parametrize(\"field_data_dict\", [\"warvictimsfund\"])\n    def test_input(field_data_dict):\n        contact_page = ContactForm(driver)\n>       contact_page.input_field(driver, \"Your Name*\",field_data_dict)\nE       TypeError: ContactForm.input_field() takes 2 positional arguments but 4 were given\n\ntests\\test_contact_form.py:27: TypeError"}, "parameters": [{"name": "field_data_dict", "value": "'warvictimsfund'"}], "start": 1708226844468, "stop": 1708226844468, "uuid": "b8029873-30bf-4722-8660-13aa543a53e6", "historyId": "1a82a448b3e6cdb12cf139c1ae75cf83", "testCaseId": "938ec7942806b96867ac01ccf953ed7f", "fullName": "tests.test_contact_form#test_input", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_contact_form"}, {"name": "host", "value": "udav_comp"}, {"name": "thread", "value": "9868-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_contact_form"}]}